projects:
  reacttodo:
    schemaPath: >-
      C:/Users/szude/repos/react-todo/react-todo/src/src/server/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
